OUTPUT_ARCH(riscv)
ENTRY(_start)

SECTIONS
{
    /* 宏配置：默认 0x40200000，可由 build.rs 注入的 -defsym=BASE_ADDRESS=... 覆盖 */
    . = DEFINED(BASE_ADDRESS) ? BASE_ADDRESS : 0x40200000;
    skernel = .;

    stext = .;
    .text : {
        *(.text.entry)
        *(.text .text.*)
    }

    . = ALIGN(4K);
    etext = .;
    srodata = .;
    .rodata : {
        *(.rodata .rodata.*)
        *(.srodata .srodata.*)
    }

    . = ALIGN(4K);
    erodata = .;
    sdata = .;
    .data : {
        *(.data .data.*)
        *(.sdata .sdata.*)
    }

    . = ALIGN(4K);
    edata = .;
    .bss : {
        *(.bss.stack)
        sbss = .;
        *(.bss .bss.*)
        *(.sbss .sbss.*)
    }

    . = ALIGN(4K);
    ebss = .;
    ekernel = .;

    /DISCARD/ : {
        *(.eh_frame)
    }
}/* lds-change */
/* lds-change-2 */
